apiVersion: v1
kind: Service
metadata:
  name: comingsoon-page
  namespace: comingsoon
spec:
  selector:
    app: comingsoon-page
# service types : ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports: #listens to more than a port ex:tcp/udp ...
  - protocol: TCP
    port: 80 
    targetPort: 80 